2024-12-22 14:02:35,320 - INFO - Starting data loading process from C:\Users\spinz\Documents\Portafolio Oficial\HERMESDB\data\raw
2024-12-22 14:02:35,327 - INFO - Found 50 CSV files to process
2024-12-22 14:02:35,559 - ERROR - Fatal error in data loading process: A process in the process pool was terminated abruptly while the future was running or pending.
2024-12-22 14:02:35,560 - ERROR - Failed to load data: A process in the process pool was terminated abruptly while the future was running or pending.
2024-12-22 14:03:07,177 - INFO - Starting data loading process from C:\Users\spinz\Documents\Portafolio Oficial\HERMESDB\data\raw
2024-12-22 14:03:07,185 - INFO - Found 50 CSV files to process
2024-12-22 14:03:07,361 - ERROR - Fatal error in data loading process: A process in the process pool was terminated abruptly while the future was running or pending.
2024-12-22 14:03:07,361 - ERROR - Failed to load data: A process in the process pool was terminated abruptly while the future was running or pending.
2024-12-22 14:06:02,796 - INFO - Starting data loading process from C:\Users\spinz\Documents\Portafolio Oficial\HERMESDB\data\raw
2024-12-22 14:06:02,802 - INFO - Found 50 CSV files to process
2024-12-22 14:06:02,904 - ERROR - Fatal error in data loading process: A process in the process pool was terminated abruptly while the future was running or pending.
Traceback (most recent call last):
  File "C:\Users\spinz\AppData\Local\Temp\ipykernel_13060\1246225650.py", line 150, in load_dataframes
    batch_results = future.result()
                    ^^^^^^^^^^^^^^^
  File "c:\Users\spinz\anaconda3\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\spinz\anaconda3\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

2024-12-22 14:06:02,905 - ERROR - Failed to load data: A process in the process pool was terminated abruptly while the future was running or pending.
2024-12-22 14:13:23,908 - ERROR - Error en la ejecución principal: La carpeta base 'c:\Users\spinz\Documents\Portafolio Oficial\HERMESDB\test\data\raw' no existe.
2024-12-22 14:14:02,479 - ERROR - Error en la ejecución principal: '1D'
